backend/ShopDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('recommend/', include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email_verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('', views.index, name='index')


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="KernShop API ",
        default_version="v1",
        description="KernShop API description",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="kernshop@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # products
    path('products/', views.ProductListApiView.as_view(), name='products '),
    path("products/<int:pk>/", views.ProductDetailAPIView.as_view()),
    # reviews
    path('reviews/create/', views.ReviewCreateView.as_view()),
    # users
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # docs
    path('swagger/', schema_view.with_ui('swagger',
                                         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
                                       cache_timeout=0), name='schema-redoc'),
]

backend/staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    # products
    path('', views.ProductListView.as_view(), name='products'),
    path('product/<slug:slug>/', views.product_detail_view, name='product-detail'),
    path('add_product/', views.ProductAddView.as_view(), name='add_product'),
    path('change_product/<slug:slug>', views.change_product, name='change_product'),
    path('delete_product/<slug:slug>', views.delete_product, name='delete_product'),
    path('search_product/', views.search_products, name='search_products'),

    # orders
    path('orders_active/', views.ActiveOrderListView.as_view(), name='active_orders'),
    path('orders_completed/', views.CompletedOrderListView.as_view(), name='completed_orders'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('order_cancel/<int:order_id>', views.order_cancel, name='order_cancel'),

    # email sending
    path('mailing/', views.email_sending, name='mailing'),
    path('mail_promo_template/', views.set_promo_mail_template, name='set_email_template'),

    # promos
    path('promo/', views.list_promo, name='promo'),
    path('add_promo/', views.add_promo, name='add_promo'),
    path('deactivate_promo/<slug:coupon_id>', views.deactivate_promo, name='deactivate_promo'),
]

backend/shop/models.py
import random
import string

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Sum
from django.utils.text import slugify
from django.urls import reverse


def rand_slug():
    """Returns random slug"""
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))


class Category(models.Model):
    name = models.CharField('Категория', max_length=250, db_index=True)
    parent = models.ForeignKey('self', verbose_name='Родительская категория', on_delete=models.CASCADE,
                               related_name='children', blank=True, null=True)
    slug = models.SlugField('URL', max_length=250, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        """
        Returns str representation of category and their parents(if exists)
        """
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:category-list', kwargs={'slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    title = models.CharField('Название', max_length=250)
    brand = models.CharField('Бренд', max_length=250)
    description = models.TextField('Описание', blank=True)
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2, default=999.99)
    image = models.ImageField('Изображение', upload_to='images/products/%Y/%m/%d',
                              default='images/products/default.jpg')
    available = models.IntegerField('Наличие', default=10, blank=False, null=True)
    slug = models.SlugField('URL', max_length=250)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата изменения', auto_now=True)
    discount = models.IntegerField('Акция',
                                   default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    rating = models.DecimalField('Рейтинг', null=True, blank=True, max_digits=3, decimal_places=2)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_rating(self):
        """Counting average rating"""
        count = self.reviews.count()
        if count > 0:
            sum = int(list(self.reviews.aggregate(Sum('rating')).values())[0])
            self.rating = round(float(sum / count), 2)
            return self.rating

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + self.title)
        super(Product, self).save(*args, **kwargs)

    def lower_available(self, quantity):
        self.available -= quantity
        return self.available

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[str(self.slug)])

    def get_discounted_price(self):
        """
        Returns product price with discount
        """
        discounted_price = self.price - (self.price * self.discount / 100)
        return round(discounted_price, 2)

    @property
    def full_image_url(self):
        """
        Returns image url
        """
        return self.image.url if self.image else ''


class ProductManager(models.Manager):
    """Returns all available products"""

    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(available__gt=0)


class ProductProxy(Product):
    objects = ProductManager()

    class Meta:
        proxy = True

backend/staff/models.py
from django.db import models

# Create your models here.

backend/staff/forms.py
from django import forms

from shop.models import Product


class ProductChangeForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['rating', 'slug', 'created_at', 'updated_at']


class CancelOrderForm(forms.Form):
    title = forms.CharField(label='Причина', max_length=100)
    send_coupon = forms.BooleanField(label='Отправить промокод клиенту', required=False)


class MailSendingForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=100)
    mail = forms.CharField(label='Письмо', widget=forms.Textarea)


class PromoCreatingForm(forms.Form):
    CHOICES = (
        ('10', '10%'),
        ('20', '20%'),
        ('30', '30%'),
    )

    sale = forms.ChoiceField(label='Процент скидки', choices=CHOICES)
    expires_on = forms.DateField(label='Действует до',
                                 widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
                                 input_formats=["%Y-%m-%d"])
    send_email = forms.BooleanField(label='Разослать его клиентам?', required=False, initial=False)
    title = forms.CharField(label='Заголовок', max_length=100, required=False,
                            widget=forms.TextInput({'placeholder': 'Заголовок', 'display': 'none'}))
    mail = forms.CharField(label='''Письмо.
    {sale} - сумма скидки или её процент, {promo} - промокод.
    Заполнять их не нужно, значения подставятся сами. НЕ МЕНЯТЬ НАЗВАНИЯ ВНУТРИ {}''',
                           widget=forms.Textarea({'placeholder': 'Письмо', 'display': 'none'}), required=False)

backend/staff/views.py
import stripe
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.utils.dateformat import format
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from braces.views import GroupRequiredMixin

from shop.models import Product
from payment.models import Order
from shop.models import Category

from .tasks import send_cancel_order_mail, mail_sending
from .forms import ProductChangeForm, MailSendingForm, CancelOrderForm, PromoCreatingForm


def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""

    def in_groups(u):
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False

    return user_passes_test(in_groups, login_url='403')


class ProductListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    model = Product
    context_object_name = 'products'
    paginate_by = 15
    group_required = [u'staff', ]

    def get_template_names(self):
        if self.request.htmx:
            return "staffshop/components/product_list.html"
        return "staffshop/products.html"


class ProductAddView(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    model = Product
    group_required = [u'staff', ]
    success_url = reverse_lazy('staff:products')
    form_class = ProductChangeForm
    template_name = 'staffshop/product_change.html'


def product_detail_view(request, slug):
    product = get_object_or_404(
        Product.objects.select_related('category'), slug=slug)
    context = {'product': product}
    return render(request, 'staffshop/product_detail.html', context)


def search_products(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query).distinct()
    context = {'products': products}
    if not query or not products:
        messages.error(
            request, 'К сожалению, нам ничего не удалось найти по вашему запросу!'
        )
        return redirect('staff:products')
    return render(request, 'staffshop/search_products.html', context)


class ActiveOrderListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    context_object_name = 'orders'
    group_required = [u'staff', ]
    template_name = 'stafforders/orders.html'
    extra_context = {'title': 'Активные заказы'}

    def get_queryset(self):
        return Order.objects.filter(status__in=['Оплачен', 'Подтвержден', 'В пути'])


class CompletedOrderListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    context_object_name = 'orders'
    group_required = [u'staff', ]
    template_name = 'stafforders/orders.html'
    extra_context = {'title': 'Завершенные заказы'}

    def get_queryset(self):
        return Order.objects.filter(status__in=['Доставлен', 'Отменен'])


@group_required('staff')
def order_detail(request, order_id):
    order = Order.objects.filter(pk=order_id).first()
    if request.method == 'POST':  # изменяем статус заказа
        if order.status == 'Оплачен':
            order.status = 'Подтвержден'
        elif order.status == 'Подтвержден':
            order.status = 'В пути'
        elif order.status == 'В пути':
            order.status = 'Доставлен'
            order.complete_order()
        else:
            messages.error(
                request, 'Заказ не оплачен, подтвердить можно только после оплаты!'
            )
        order.save()
    return render(request, 'stafforders/order_detail.html', {'order': order})


@group_required('staff')
def order_cancel(request, order_id):
    order = Order.objects.filter(pk=order_id).first()
    form = CancelOrderForm()
    if request.method == 'POST':
        form = CancelOrderForm(request.POST)
        if form.is_valid():
            order.status = 'Отменен'
            order.complete_order()
            order.cancel_reason = form.cleaned_data['title']
            order.save()
            title = form.cleaned_data['title']
            coupon = form.cleaned_data['send_coupon']
            send_cancel_order_mail.delay(order_id, title=title, coupon=coupon)
            return redirect('staff:order_detail', order_id=order_id)
    return render(request, 'stafforders/order_cancel.html', {'order': order, 'form': form})


@group_required('staff')
def change_product(request, slug):
    product = get_object_or_404(Product.objects.select_related('category'), slug=slug)
    if request.method == 'POST':
        form = ProductChangeForm(request.POST, instance=product)
        form.save()
        return redirect('staff:products')
    else:
        form = ProductChangeForm(instance=product)

    return render(request, 'staffshop/product_change.html', {'form': form})


@group_required('staff')
def delete_product(request, slug):
    product = get_object_or_404(Product.objects.select_related('category'), slug=slug)
    if request.method == 'POST':
        product.delete()
        return redirect('staff:products')
    return render(request, 'staffshop/product_delete.html', {'product': product})


@group_required('staff')
def email_sending(request):
    form = MailSendingForm()
    if request.method == 'POST':
        form = MailSendingForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            mail = form.cleaned_data['mail']
            mail_sending.delay(title, mail)
            messages.success(request,
                             'Рассылка успешно отправлена! Скоро получатели получат её!')
    return render(request, 'mailing/mail_sender.html', {'form': form})


@group_required('staff')
def list_promo(request):
    promos = stripe.PromotionCode.list()
    return render(request, 'promo/promos.html', {'promos': promos})


@group_required('staff')
def add_promo(request):
    form = PromoCreatingForm()
    if request.method == 'POST':
        form = PromoCreatingForm(request.POST)
        if form.is_valid():
            date = format(form.cleaned_data['expires_on'], 'U')  # convers datetime to unix format
            coupon = stripe.PromotionCode.create(
                coupon=f'sale{form.cleaned_data["sale"]}',
                expires_at=format(form.cleaned_data['expires_on'], 'U')
            )
            if form.cleaned_data['send_email']:
                if form.cleaned_data['title'] and form.cleaned_data['mail']:
                    title = form.cleaned_data['title']
                    mail = form.cleaned_data['mail'].format(sale=coupon.coupon.percent_off, promo=coupon.code)
                    mail_sending.delay(title, mail)
                else:
                    messages.error(request, 'Заполните данные для письма!')
            messages.success(request, f'Промокод {coupon.code} успешно создан!')
    return render(request, 'promo/promo_form.html', {'form': form})


@group_required('staff')
def set_promo_mail_template(request):
    # template to send promo mail
    if request.method == 'GET':
        title = 'НОВАЯ АКЦИЯ! УСПЕЙ, ПОКА ВСЕ НЕ РАЗОБРАЛИ!'
        mail = 'У нас есть персональный подарок для тебя! Активируй наш новый промокод и получи скидку - {sale}. ' \
               'Используй промокод {promo} при следующей покупке!'

        response = JsonResponse({'title': title, 'mail': mail})
        return response


@group_required('staff')
def deactivate_promo(request, coupon_id):
    coupon = stripe.PromotionCode.retrieve(coupon_id)
    coupon.active = False
    coupon.save()
    messages.success(request, f'Промокод "{coupon.code}" успешно деактивирован!')
    return redirect('staff:promo')

backend/staff/templates/staffshop/product_change.html
{%  extends "staff_layout.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container bg-white shadow-md p-5 form-layout">
    
    <h3>Редактирование</h3>
    
    <br>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary w-100 btn-block p-2 btn-register">Сохранить</button>
    </form>

    <br>

    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                
            </li>
        {% endfor %}
    </ul>
{% endif %}

    
</div>

<br>

{% endblock content %}

backend/staff/templates/staffshop/product_delete.html
{%  extends "staff_layout.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container bg-white shadow-md p-5 form-layout">
    
    <h3>Удаление</h3>
    
    <br>

    <form method="post">
        {% csrf_token %}
        <h4>Вы уверены что хотите удалить {{ product.title }}? Восстановить его не получиться!</h4>
        <button type="submit" class="btn btn-secondary w-100 btn-block p-2 btn-register">Удаление</button>
    </form>

    <br>

    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                
            </li>
        {% endfor %}
    </ul>
{% endif %}

    
</div>

<br>

{% endblock content %}

backend/staff/templates/staffshop/product_detail.html
{% extends "staff_layout.html" %}

{% load static %}
{% load thumbnail %}
{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                {% thumbnail product.image "400x400" as im %}
                    <img class="img-fluid h-100" alt="Responsive image" src="{{ im.url }}" />
                {% endthumbnail %}

            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{product.title}}</h1>
                <hr>

                <strong>{{product.brand}}</strong>


                <hr>

                <br>


                <p> {{product.description}} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">

                            <div class="col-6"> Цена </div>
                            {% if product.discount %}
                            <div class="col-6 text-end"><span class="text-decoration-line-through fw-bold text-danger">{{product.price}} <span class="badge rounded-pill bg-info">скидка</span></span> <span class="h4 fw-bold">{{product.get_discounted_price}}</span></div>
                            {% else%}
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{product.price}}</span></div>
                            {% endif %}

                        </div>

                    </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <br>
</div>



{% endblock %}

backend/staff/templates/staffshop/products.html
{% extends 'staff_layout.html' %}

{% load thumbnail %}


{% block content %}

    <div class="pb-3 h5" style="margin-left: 100px; margin-top: 40px">Все продукты</div>

    <hr />

    <br />
     <form action="{% url 'staff:search_products' %}" method="get" style="width: max-content; margin-left: 50px">
            <div class="input-group rounded">
              <input type="search" name="q" class="form-control rounded" placeholder="Поиск" aria-label="Search" aria-describedby="search-addon" />
              <span class="input-group-text border-0" id="search-addon">
                <button class="btn btn-secondary search-button">Поиск</button>
              </span>
            </div>
        </form>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3" style="margin: 100px 100px">

      {% include 'staffshop/components/product_list.html' %}
    </div>
  </div>
</section>
{% endblock %}

backend/staff/templates/staffshop/search_products.html
{% extends 'staff_layout.html' %}

{% load thumbnail %}

{% block content %}


<section class="album py-5 bg-light">
  <div class="container">
    <div class="pb-3 h5">Найденные товары:</div>

    <hr />

    <br />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
            <a class="text-black text-decoration-none fs-4" href="{{product.get_absolute_url}}">
            <div class="card shadow-sm h-100">
                {% thumbnail product.image "400x400" as im %}
                    <div style="position: relative">
                              {% if product.discount %}
                    <div class="sale" style="background-color: green; width: max-content; color: white;
                border-radius: 5px; margin: 5px; font-size: 20px; padding: 5px; position: absolute">SALE {{ product.discount }}%</div>
                    {% endif %}
                {% if product.rating %}
                    <div class="rating" style="position: absolute; right: 0px; margin: 5px; margin-left: auto; background-color: gold
; border-radius: 5px; padding: 5px">&#9733; {{ product.rating }}</div>
                {% endif %}
                    <img class="img-fluid h-100" alt="Responsive image" src="{{ im.url }}" />
                    </div>
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text">
                        {{product.title|capfirst}}
                    </p>
                <div class="prod_change"><a href="{% url 'staff:change_product' product.slug %}">Изменить</a>
                        <a href="{% url 'staff:delete_product' product.slug %}">Удалить</a></div>
                    <div class="d-flex justify-content-between align-items-center badge search-button text-wrap text-dark"
                        style="width: 6rem">
                        {% if product.discount %}
                            <span class="text-decoration-line-through fw-bold text-danger"><h5>{{product.price}}</h5></span>
                            <span class="h6 fw-bold" style="margin-left: 40px"><h3>{{product.get_discounted_price}}</h3></span>
                        {% else %}
                        <h5>{{product.price}}</h5>
                        {% endif %}
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
{% endblock %}