backend/ShopDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('recommend/', include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email_verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('', views.index, name='index')


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="KernShop API ",
        default_version="v1",
        description="KernShop API description",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="kernshop@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # products
    path('products/', views.ProductListApiView.as_view(), name='products '),
    path("products/<int:pk>/", views.ProductDetailAPIView.as_view()),
    # reviews
    path('reviews/create/', views.ReviewCreateView.as_view()),
    # users
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # docs
    path('swagger/', schema_view.with_ui('swagger',
                                         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
                                       cache_timeout=0), name='schema-redoc'),
]

backend/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add/', views.cart_add, name='add-to-cart'),
    path('delete/', views.cart_delete, name='delete-to-cart'),
    path('update/', views.cart_update, name='update-to-cart'),
]

backend/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # path('', views.products_view, name='products'),
    path('', views.ProductListView.as_view(), name='products'),
    path('sales/', views.SalesListView.as_view(), name='sales'),
    path("search_products/", views.search_products, name="search-products"),
    path('<slug:slug>/', views.product_detail_view, name='product-detail'),
    path('category/<slug:slug>', views.categories_list, name='category-list'),
]

backend/shop/models.py
import random
import string

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Sum
from django.utils.text import slugify
from django.urls import reverse


def rand_slug():
    """Returns random slug"""
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))


class Category(models.Model):
    name = models.CharField('Категория', max_length=250, db_index=True)
    parent = models.ForeignKey('self', verbose_name='Родительская категория', on_delete=models.CASCADE,
                               related_name='children', blank=True, null=True)
    slug = models.SlugField('URL', max_length=250, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        """
        Returns str representation of category and their parents(if exists)
        """
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:category-list', kwargs={'slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    title = models.CharField('Название', max_length=250)
    brand = models.CharField('Бренд', max_length=250)
    description = models.TextField('Описание', blank=True)
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2, default=999.99)
    image = models.ImageField('Изображение', upload_to='images/products/%Y/%m/%d',
                              default='images/products/default.jpg')
    available = models.IntegerField('Наличие', default=10, blank=False, null=True)
    slug = models.SlugField('URL', max_length=250)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата изменения', auto_now=True)
    discount = models.IntegerField('Акция',
                                   default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    rating = models.DecimalField('Рейтинг', null=True, blank=True, max_digits=3, decimal_places=2)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_rating(self):
        """Counting average rating"""
        count = self.reviews.count()
        if count > 0:
            sum = int(list(self.reviews.aggregate(Sum('rating')).values())[0])
            self.rating = round(float(sum / count), 2)
            return self.rating

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + self.title)
        super(Product, self).save(*args, **kwargs)

    def lower_available(self, quantity):
        self.available -= quantity
        return self.available

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[str(self.slug)])

    def get_discounted_price(self):
        """
        Returns product price with discount
        """
        discounted_price = self.price - (self.price * self.discount / 100)
        return round(discounted_price, 2)

    @property
    def full_image_url(self):
        """
        Returns image url
        """
        return self.image.url if self.image else ''


class ProductManager(models.Manager):
    """Returns all available products"""

    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(available__gt=0)


class ProductProxy(Product):
    objects = ProductManager()

    class Meta:
        proxy = True

backend/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.db.models import Q
from django.contrib import messages
from .models import Category, ProductProxy
from payment.models import OrderItem


class ProductListView(ListView):
    model = ProductProxy
    context_object_name = 'products'
    paginate_by = 15

    def get_template_names(self):
        if self.request.htmx:
            return "shop/components/product_list.html"
        return "shop/products.html"


class SalesListView(ListView):
    context_object_name = 'products'
    template_name = 'shop/search_products.html'

    def get_queryset(self):
        sales = ProductProxy.objects.filter(discount__gt=0).order_by('-discount')
        return sales


def product_detail_view(request, slug):
    product = get_object_or_404(
        ProductProxy.objects.select_related('category'), slug=slug)
    try:
        # getting information about user's review on this product and did he order this product
        buyer = OrderItem.objects.filter(Q(product=product) & Q(user=request.user))
        check_reviews = product.reviews.filter(created_by=request.user).exists()
    except TypeError:
        # if not - setting false
        buyer, check_reviews = False, False
    finally:
        if request.method == 'POST':
            if request.user.is_authenticated:
                if check_reviews:
                    messages.error(
                        request, 'Вы уже оставляли отзыв на этот продукт')
                elif not buyer:
                    messages.error(
                        request, 'Вы можете оставить отзыв только на купленный продукт!')
                else:
                    rating = request.POST.get('rating', 3)
                    content = request.POST.get('content', '')
                    if content:
                        # creating review
                        product.reviews.create(
                            rating=rating, content=content, created_by=request.user, product=product)
                        product.get_rating()
                        product.save()
                        return redirect(request.path)
            else:
                messages.error(
                    request, 'Вы должны быть авторизованы, чтобы оставить отзыв')

        context = {'product': product, 'buyer': buyer, 'check_reviews': check_reviews}
    return render(request, 'shop/product_detail.html', context)


def categories_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = ProductProxy.objects.select_related('category').filter(category=category)
    context = {'category': category, 'products': products}
    return render(request, 'shop/category_list.html', context)


def search_products(request):
    query = request.GET.get('q')
    products = ProductProxy.objects.filter(title__icontains=query).distinct()
    context = {'products': products}
    if not query or not products:
        messages.error(
            request, 'К сожалению, нам ничего не удалось найти по вашему запросу!'
        )
        return redirect('shop:products')
    return render(request, 'shop/search_products.html', context)

backend/shop/templates/shop/category_list.html
{% extends "layout.html" %}

{% load static %}


{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{category.name|capfirst}} </div>


      <hr>

      <br>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-info text-decoration-none" href="{{product.get_absolute_url}}"> {{product.title|capfirst}} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <h5> $ {{product.price}} </h5>
              </div>
            </div>
          </div>
        </div>

       {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

backend/shop/templates/shop/product_detail.html
{% extends "layout.html" %}

{% load static %}
{% load thumbnail %}
{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                {% thumbnail product.image "400x400" as im %}
                    <img class="img-fluid h-100" alt="Responsive image" src="{{ im.url }}" />
                {% endthumbnail %}

            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{product.title}}</h1>
                <hr>

                <strong>{{product.brand}}</strong>


                <hr>

                <br>


                <p> {{product.description}} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">

                            <div class="col-6"> Цена </div>
                            {% if product.discount %}
                            <div class="col-6 text-end"><span class="text-decoration-line-through fw-bold text-danger">{{product.price}} <span class="badge rounded-pill bg-info">скидка</span></span> <span class="h4 fw-bold">{{product.get_discounted_price}}</span></div>
                            {% else%}
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{product.price}}</span></div>
                            {% endif %}

                        </div>

                    </div>

                    <div class="col">

                        <div class="row p-3">

                            <div class="col-6">


                                <label for="select">Количество</label>

                                &nbsp;

                                <select id="select">

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                </select>

                            </div>

                            <div class="col-6 text-end">

                                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">

                                Добавить в корзину

                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <br>
    {% include 'recommend/recommendation.html' %}
</div>
<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:add-to-cart" %}',
            data: {
                product_id: $('#add-button').val(),
                product_qty: $('#select option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function (response) {
                document.getElementById('lblCartCount').textContent = response.qty
                const add_button = document.getElementById('add-button')
                add_button.disabled = true
                add_button.innerText = "Добавлен в корзину"
                add_button.className = "btn btn-success btn-sm"

            },
            error: function (error) {
                console.log(error)
            }
        })

    })


</script>


{% endblock %}

backend/shop/templates/shop/products.html
{% extends 'layout.html' %}

{% load thumbnail %}
{% load shoptags %}


{% block content %}


    {% get_sale_products %}

    {% get_most_rated_products %}

    <div class="pb-3 h5">Все продукты</div>

    <hr />

    <br />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% include 'shop/components/product_list.html' %}
    </div>
  </div>
</section>
{% endblock %}

backend/shop/templates/shop/search_products.html
{% extends 'layout.html' %}

{% load thumbnail %}

{% block content %}


<section class="album py-5 bg-light">
  <div class="container">
    <div class="pb-3 h5">Найденные товары:</div>

    <hr />

    <br />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
            <a class="text-black text-decoration-none fs-4" href="{{product.get_absolute_url}}">
            <div class="card shadow-sm h-100">
                {% thumbnail product.image "400x400" as im %}
                    <div style="position: relative">
                              {% if product.discount %}
                    <div class="sale" style="background-color: green; width: max-content; color: white;
                border-radius: 5px; margin: 5px; font-size: 20px; padding: 5px; position: absolute">SALE {{ product.discount }}%</div>
                    {% endif %}
                {% if product.rating %}
                    <div class="rating" style="position: absolute; right: 0px; margin: 5px; margin-left: auto; background-color: gold
; border-radius: 5px; padding: 5px">&#9733; {{ product.rating }}</div>
                {% endif %}
                    <img class="img-fluid h-100" alt="Responsive image" src="{{ im.url }}" />
                    </div>
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text">
                        {{product.title|capfirst}}
                    </p>
                    <div class="d-flex justify-content-between align-items-center badge search-button text-wrap text-dark"
                        style="width: 6rem">
                        {% if product.discount %}
                            <span class="text-decoration-line-through fw-bold text-danger"><h5>{{product.price}}</h5></span>
                            <span class="h6 fw-bold" style="margin-left: 40px"><h3>{{product.get_discounted_price}}</h3></span>
                        {% else %}
                        <h5>{{product.price}}</h5>
                        {% endif %}
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
{% endblock %}